all:
	docker build -t agrdocker/agr_loader_env .

push:
	docker push agrdocker/agr_loader_env

pull:
	docker pull agrdocker/agr_loader_env

bash:
	docker run -t -i agrdocker/agr_loader_env bash

run:
	docker run -t -i agrdocker/agr_loader_env
