SPECIES: [Species]
# Add human so we get Cross references?
BGI: [MGI, HUMAN]
AGM: [MGI]
ALLELE: [MGI]
# not really bit want to check construct etl.
CONSTRUCT: [MGI]
# Loader configuration values are below.
# Please modify with caution!
ONTOLOGY:
  - SO
  - DOID
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
  - ECOMAP
  - PATO
  - APO
  - DPO
  - FYPO
  - WBPhenotype
  - MP
  - HP
  - OBI
  - BTO
  - CHEBI
FileTransactorThreads: 10
Neo4jTransactorThreads: 7
