from .bgi_loader import BGILoader
from .do_loader import DOLoader
from .go_loader import GOLoader
from .go_annot_loader import GOAnnotLoader
from .so_loader import SOLoader
from .ortho_loader import OrthoLoader
from .disease_loader import DiseaseLoader
from .geo_loader import GeoLoader
from .mi_loader import MILoader
from .imex_loader import IMEXLoader
from .phenotype_loader import PhenotypeLoader
from .wt_expression_loader import WTExpressionLoader
from .cl_loader import CLLoader
from emapa_loader import EMAPALoader
from fbbt_loader import FBBTLoader
from fbdv_loader import FBDVLoader
from ma_loader import MALoader
from uberon_loader import UBERONLoader
from wbbt_loader import WBBTLoader
from zfa_loader import ZFALoader