from .bgi_loader import BGILoader
from .do_loader import DOLoader
from .go_loader import GOLoader
from .go_annot_loader import GOAnnotLoader
from .so_loader import SOLoader
from .ortho_loader import OrthoLoader
from .disease_loader import DiseaseLoader
from .geo_loader import GeoLoader
from .mi_loader import MILoader
from .phys_int_loader import PhysIntLoader
from .phenotype_loader import PhenotypeLoader