name: Test SSH Tunnel Setup

on:
  push:
    branches:
      - fb_ansible_test

jobs:
  ssh-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH agent and add keys
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY_1 }}
          ${{ secrets.SSH_PRIVATE_KEY_2 }}

    - name: Add gateway host to known hosts
      run: echo "${{ secrets.GATEWAY_HOST_KEY }}" >> ~/.ssh/known_hosts

    - name: Add target host to known hosts
      run: echo "${{ secrets.TARGET_HOST_KEY }}" >> ~/.ssh/known_hosts

    - name: Create SSH tunnel
      run: |
        ssh -v -o StrictHostKeyChecking=no -f -N -L 8153:localhost:8153 -o ServerAliveInterval=15 -J ${{ secrets.GATEWAY_USER }}@${{ secrets.GATEWAY_HOST }} ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }}

    - name: Test SSH tunnel
      run: |
        ssh -v -o StrictHostKeyChecking=no -p 8153 ${{ secrets.TARGET_USER }}@localhost "echo Connected to target host through tunnel"
